version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    expose:
      - "27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    expose:
      - "3000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - MONGO_URL=http://mongo:27017
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3001:80" # Nginx serves the production build on port 80
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:3000
    networks:
      - app-network

volumes:
  mongo-data:
networks:
  app-network:
    driver: bridge
