version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3001:80" # Nginx serves the production build on port 80
    depends_on:
      - backend

volumes:
  mongo-data:
